Repository tams-cso/tams-club-cal, pull requests merged in 2021-01, with the labels that each got.

#98 Added info to README on frontend vs backend development
  README.md
Labels: documentation

#169 Add new scss formatting guidelines and formatted scss
  CONTRIBUTING.md
  client/src/components/ActionButton.js
  client/src/components/ActionButton.scss
  client/src/components/ClubCard.js
  client/src/components/ClubCard.scss
  client/src/components/ClubPopup.js
  client/src/components/CommitteeCard.js
  client/src/components/CommitteeCard.scss
  client/src/files/web.svg
Labels: css, organization

#174 Wrap fetch calls in try/catch blocks
  client/src/functions/api.js
Labels: frontend, new feature, organization

#178 Events page only shows current and upcoming events
  client/src/pages/Home.js
Labels: frontend, new feature

#179 Get timezone from client
  client/src/components/EventPopup.js
  client/src/functions/util.js
  client/src/pages/Add.js
Labels: frontend

#181 Make date headers on events sticky when scrolling and fix home-top
  client/src/App.scss
  client/src/components/DateSection.scss
  client/src/pages/Home.js
  client/src/pages/Home.scss
Labels: css, frontend, new feature

#183 Add features to calendar
  client/src/components/CalendarDay.js
  client/src/components/CalendarDay.scss
  client/src/pages/Home.js
  client/src/pages/Home.scss
Labels: frontend, new feature

#189 Fix invalid popup state by checking url
  client/src/components/EventPopup.js
  client/src/components/Popup.js
  client/src/functions/util.js
Labels: frontend

#192 Fix css formatting
  client/src/components/CalendarEvent.js
  client/src/components/CalendarEvent.scss
  client/src/components/ExecCard.scss
  client/src/components/ScheduleEvent.scss
  client/src/pages/Home.scss
Labels: css, organization

#194 You can now add volunteering events!
  client/src/components/Popup.js
  client/src/components/VolunteeringCard.scss
  client/src/components/VolunteeringPopup.js
  client/src/custom.scss
  client/src/functions/api.js
  client/src/functions/entries.js
  client/src/pages/Resources.js
  client/src/pages/Resources.scss
  client/src/redux/actionTypes.js
  client/src/redux/actions.js
  client/src/redux/reducers/data.js
  client/src/redux/reducers/popup.js
  client/src/redux/selectors.js
  server/src/app.js
  server/src/database.js
Labels: frontend, new feature

#201 Fix className conflicts and reference issues
  client/src/components/CalendarDay.js
  client/src/components/CalendarDay.scss
  client/src/pages/Home.scss
Labels: bug, css

#228 addedBy field gone, replaced by editedBy for events
  client/src/components/EventPopup.js
  client/src/components/EventPopup.scss
  client/src/functions/entries.js
  client/src/pages/Add.js
  server/src/database.js
Labels: frontend

#227 Page no longer scrolls when popup closes
  client/src/components/Menu.js
Labels: frontend

#232 Mobile Compatibility SCSS Overhaul
  client/src/App.js
  client/src/App.scss
  client/src/components/ClubCard.scss
  client/src/components/DateSection.scss
  client/src/components/ExecCard.scss
  client/src/components/ScheduleEvent.scss
  client/src/components/SearchBar.scss
  client/src/custom.scss
  client/src/files/logo-banner.png
  client/src/files/logo-small.svg
  client/src/pages/About.js
  client/src/pages/About.scss
  client/src/pages/Add.js
  client/src/pages/Add.scss
  client/src/pages/Clubs.js
  client/src/pages/Clubs.scss
  client/src/pages/Home.js
  client/src/pages/Home.scss
  client/src/pages/Menu.js
  client/src/pages/Menu.scss
  client/src/pages/Resources.js
  client/src/pages/Resources.scss
  client/src/popups/ClubPopup.js
  client/src/popups/ClubPopup.scss
  client/src/popups/EventPopup.js
  client/src/popups/EventPopup.scss
  client/src/popups/Popup.js
  client/src/popups/Popup.scss
  client/src/popups/VolunteeringPopup.js
  client/src/popups/VolunteeringPopup.scss
Labels: css, organization
