Repository tams-cso/tams-club-cal, pull requests merged in 2021-03, with the labels that each got.

#268 HOTFIX: popups now work through search
  client/src/components/menu/search.js
Labels: bug, frontend

#289 Updated database docs
  docs/database/data-db.md
Labels: documentation

#294 Added min height to popup
  client/src/components/home/event-popup.scss
Labels: css

#298 Add transition and border radius to calendar events
  client/src/components/home/calendar-event.scss
Labels: css

#301 Added beta dark theme!
  client/src/app.js
  client/src/app.scss
  client/src/components/about/about.scss
  client/src/components/home/calendar-day.js
  client/src/components/home/calendar.js
  client/src/components/home/date-section.js
  client/src/components/shared/action-button.js
  client/src/custom.scss
Labels: css

#317 Added text to diff between staging and production apps
  client/src/app.js
  client/src/app.scss
Labels: frontend

#318 Edit Events Optimizations
  client/src/components/edit/edit-events.js
Labels: frontend

#319 Popup fixes
  client/src/components/clubs/club-card.scss
  client/src/components/clubs/club-popup.scss
  client/src/components/clubs/committee-card.scss
  client/src/components/clubs/exec-card.scss
  client/src/components/edit/edit-clubs.scss
  client/src/components/home/event-popup.scss
  client/src/components/shared/popup.js
  client/src/components/shared/popup.scss
  client/src/components/volunteering/volunteering-card.scss
  client/src/components/volunteering/volunteering-popup.js
  client/src/components/volunteering/volunteering-popup.scss
  client/src/components/volunteering/volunteering.js
Labels: css, frontend

#322 Added check for default dark theme
  client/src/app.js
Labels: frontend
